# Generated by Django 5.1.4 on 2024-12-15 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 18, 42, 54, 257449)),
        ),
    ]
