# Generated by Django 5.1.4 on 2024-12-15 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 19, 16, 39, 188902)),
        ),
    ]
