# Generated by Django 5.1.4 on 2024-12-16 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 5, 24, 45, 94482, tzinfo=datetime.timezone.utc)),
        ),
    ]
