# Generated by Django 5.1.4 on 2024-12-16 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 10, 59, 811363, tzinfo=datetime.timezone.utc)),
        ),
    ]
