# Generated by Django 5.1.4 on 2024-12-17 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 7, 2, 40, 451897, tzinfo=datetime.timezone.utc)),
        ),
    ]
