# Generated by Django 5.1.4 on 2024-12-18 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 7, 39, 11, 62728, tzinfo=datetime.timezone.utc)),
        ),
    ]
