# Generated by Django 5.1.4 on 2024-12-18 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 9, 7, 33, 167651, tzinfo=datetime.timezone.utc)),
        ),
    ]
