# Generated by Django 5.1.4 on 2024-12-20 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0022_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 8, 51, 27, 211753, tzinfo=datetime.timezone.utc)),
        ),
    ]
