# Generated by Django 5.1.4 on 2024-12-20 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0025_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 10, 24, 54, 693115, tzinfo=datetime.timezone.utc)),
        ),
    ]
