# Generated by Django 5.1.4 on 2024-12-20 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0026_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 10, 44, 44, 17459, tzinfo=datetime.timezone.utc)),
        ),
    ]
