# Generated by Django 5.1.4 on 2024-12-21 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0027_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 11, 19, 13, 345137, tzinfo=datetime.timezone.utc)),
        ),
    ]
