# Generated by Django 5.1.4 on 2025-01-12 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0028_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 7, 50, 43, 268550, tzinfo=datetime.timezone.utc)),
        ),
    ]
