# Generated by Django 5.1.4 on 2025-01-12 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0029_alter_otpcode_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 7, 56, 25, 48995, tzinfo=datetime.timezone.utc)),
        ),
    ]
