# Generated by Django 5.1.4 on 2025-01-12 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0032_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 14, 25, 48, 214655, tzinfo=datetime.timezone.utc)),
        ),
    ]
