# Generated by Django 5.1.4 on 2024-12-16 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b3d845c7-4916-4533-9e34-8278869bc15e'), max_length=255, unique=True),
        ),
    ]
