# Generated by Django 5.1.4 on 2024-12-16 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_category_reply_cat_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('17b45158-62d3-4979-9eae-9b1a7acc65b7'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d49cc44d-0f29-452c-a8ea-a0d0c704e80e'), max_length=255, unique=True),
        ),
    ]
