# Generated by Django 5.1.4 on 2024-12-16 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_product_price_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('920ffee0-9f0a-477e-8a20-8ca97f448841'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2595bff0-3c41-406b-80b3-7f0e7ab67ac5'), max_length=255, unique=True),
        ),
    ]
