# Generated by Django 5.1.4 on 2024-12-17 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('af267348-e500-4fc1-bd4b-85f8d00ef742'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('07fa392e-b2a9-450e-b59b-351967eee469'), max_length=255, unique=True),
        ),
    ]
