# Generated by Django 5.1.4 on 2024-12-17 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ba3c2898-6954-4229-b888-84a1bca5864d'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2696a565-de1e-4c50-97dc-36825efc44fb'), max_length=255, unique=True),
        ),
    ]
