# Generated by Django 5.1.4 on 2024-12-17 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d97ee326-3751-4283-b48d-b99984fee749'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c658106c-482f-49d5-be86-1e4a7edee6aa'), max_length=255, unique=True),
        ),
    ]
