# Generated by Django 5.1.4 on 2024-12-18 07:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_category_reply_cat_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('8aa5e650-c2d5-49c3-8cfb-6b8d12fac4c1'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fb970cbb-9674-42c8-af77-e568f766fe3b'), max_length=255, unique=True),
        ),
    ]
