# Generated by Django 5.1.4 on 2024-12-18 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_category_cat_img_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('f7a64216-720a-4ede-8324-7a3879613afd'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fe05dc4f-d9f5-4cbf-8263-2664123da8ca'), max_length=255, unique=True),
        ),
    ]
