# Generated by Django 5.1.4 on 2024-12-19 01:27

import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_product_quantity_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('available_products', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('21da4752-1d5e-4cec-9ed1-ea5e7a624805'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b3ff9a38-f697-492d-8d1f-bf096c2cdefd'), max_length=255, unique=True),
        ),
    ]
