# Generated by Django 5.1.4 on 2024-12-19 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_product_managers_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('29fc3d13-3ead-4902-8372-a2523132ac3c'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('211b0cd2-454d-4bea-90ee-36664812d662'), max_length=255, unique=True),
        ),
    ]
