# Generated by Django 5.1.4 on 2024-12-20 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3fde2bcd-57f6-49ac-9943-6fd796e4819f'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('48ac2dd4-3d56-4bfa-88da-3aa1369f6293'), max_length=255, unique=True),
        ),
    ]
