# Generated by Django 5.1.4 on 2024-12-20 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d5f07bb4-5dc8-4319-93f6-8c355de09ddd'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c80dac81-7d02-45c2-80ea-54b0a9f66bd0'), max_length=255, unique=True),
        ),
    ]
