# Generated by Django 5.1.4 on 2024-12-20 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ca6898a5-f924-4475-a46c-45f6e6a489c6'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ddc9a161-493c-41e9-9d32-c398c1228e1d'), max_length=255, unique=True),
        ),
    ]
