# Generated by Django 5.1.4 on 2024-12-20 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('57c4ff02-fb51-4532-a751-33265dddf1ef'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('79817a4d-bb16-4327-846a-c2310bbf2cdd'), max_length=255, unique=True),
        ),
    ]
