# Generated by Django 5.1.4 on 2024-12-20 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5218db48-b459-4a68-bf55-ad8ac6b9a649'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5d5e69a1-62e8-4bd7-b499-f85d675fafde'), max_length=255, unique=True),
        ),
    ]
