# Generated by Django 5.1.4 on 2024-12-20 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('571d0c27-700a-47a6-aac3-72440c46d4cc'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3d382f9f-77f3-4069-90f1-7d9467df38aa'), max_length=255, unique=True),
        ),
    ]
