# Generated by Django 5.1.4 on 2024-12-21 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fbb3d7e4-9bfd-4fe1-bf45-9d2241f9863f'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0ef243c6-6b94-4b50-8d20-7c00193e5968'), max_length=255, unique=True),
        ),
    ]
