# Generated by Django 5.1.4 on 2025-01-12 07:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bea1faa4-c436-4aca-bd72-ba053b7ee486'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('589e34be-67f1-43c1-87ac-1b5b912d2c64'), max_length=255, unique=True),
        ),
    ]
