# Generated by Django 5.1.4 on 2025-01-12 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fba2df9a-8bf8-40a2-a606-13e7475dff69'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7c044abd-d499-4a88-b360-5ed78c87b0e4'), max_length=255, unique=True),
        ),
    ]
