# Generated by Django 5.1.4 on 2025-01-12 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d323dcbf-b50d-4796-ac21-275aa3692e80'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5f5b85c7-4ce2-4c7d-b42c-52b8187c6b42'), max_length=255, unique=True),
        ),
    ]
