# Generated by Django 5.1.4 on 2025-01-12 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('edb1cf0a-edba-426c-9e12-881ffa62e599'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('10558b5c-e2aa-4a9f-8766-d1492dc84140'), max_length=255, unique=True),
        ),
    ]
