# Generated by Django 5.1.4 on 2025-01-12 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3ad822cf-fd63-4951-a248-8ccb613e8a97'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d56f38a0-b742-420c-aa18-7b5d1a9a1034'), max_length=255, unique=True),
        ),
    ]
