# Generated by Django 5.1.4 on 2024-12-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_baseorder_orderitem_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('from_this', models.DateTimeField()),
                ('to_this', models.DateTimeField()),
            ],
        ),
    ]
