# Generated by Django 5.1.4 on 2024-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
