# Generated by Django 5.1.4 on 2024-12-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_baseorder_discount_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='use',
            field=models.BooleanField(default=False),
        ),
    ]
